const { materialPage } = require("./material-calculator");

/* Each aggregate page opens on its own material and carries its own prose.
 * The shared sections live in material-calculator.js. */

const LINKS = {
  gravel: ["/gravel-calculator/", "Gravel Calculator"],
  mulch: ["/mulch-calculator/", "Mulch Calculator"],
  rock: ["/river-rock-calculator/", "River Rock Calculator"],
  sqft: ["/square-footage-calculator/", "Square Footage Calculator"],
  asphalt: ["/asphalt-calculator/", "Asphalt Calculator"],
  roadbase: ["/road-base-calculator/", "Road Base Calculator"],
  stone: ["/stone-calculator/", "Crushed Stone Calculator"],
  sand: ["/sand-calculator/", "Sand Calculator"],
  topsoil: ["/topsoil-calculator/", "Topsoil Calculator"],
  dirt: ["/fill-dirt-calculator/", "Fill Dirt Calculator"],
  concrete: ["/concrete-calculator/", "Concrete Calculator"],
};
const relatedTo = (...keys) => keys.map(k => LINKS[k]);

const gravel = materialPage({
  path: "/gravel-calculator/",
  h1: "Gravel Calculator",
  title: "Gravel Calculator – Yards, Tons & Cost | Ruler Square",
  description: "Free gravel calculator for driveways, paths and drainage. Get cubic yards, tons, coverage and material cost, with editable density and allowance.",
  lede: "Gravel in tons and cubic yards, what it covers, and what it costs.",
  material: "gravel",
  materialName: "Gravel",
  noun: "gravel",
  lbPerYd3: 2800, lowTons: 1.4, highTons: 1.7,
  defaultDepth: 4, defaultCompaction: 15,
  depthHint: "4 in is typical for a driveway top course",
  lastmod: "2026-09-22",
  intro: "Gravel is sold by volume in cubic yards and by weight in tons, and suppliers switch between the two without warning. Work out both before you call, and you can compare quotes that are priced in different units.",
  example: {
    label: "20 × 10 ft driveway apron, 4 inches deep",
    text: "The area is 20 × 10 = 200 square feet. Four inches is 0.333 feet, so the volume is 200 × 0.333 = 66.7 cubic feet, or 66.7 ÷ 27 = 2.47 cubic yards. It is being driven on, so add 15% for compaction: 2.84 cubic yards. Gravel runs about 1.4 tons per cubic yard, which makes that 3.98 tons. Order 3 cubic yards, or 4 tons.",
  },
  depthProse: "For gravel, depth is the difference between a driveway that lasts and one that potholes in a season. A top course spread over an existing compacted base only needs 3–4 inches. A brand new driveway built on bare soil needs three separate lifts — a coarse base, a middle course, and a finished top course — totalling 8–12 inches.",
  faq: [
    ["What size gravel is best for a driveway?",
     "Most driveways use three layers. A #3 or #4 coarse stone at the bottom for drainage, a #57 stone in the middle, and a crusher run or #411 on top, which has fines in it that lock together when compacted. Using only round pea gravel on a driveway is the most common mistake — it never locks, so it migrates into ruts and spreads into the lawn."],
    ["How much gravel do I need for a 12 x 20 ft driveway?",
     "At 4 inches deep, a 12 × 20 ft driveway (240 square feet) needs about 2.96 cubic yards or 4.1 tons of gravel. Add 15% for compaction and order roughly 3.5 cubic yards. If you are building the driveway from bare soil rather than topping up an existing one, plan on 8–12 inches total across all layers, which is closer to 9 cubic yards."],
    ["Will gravel wash away on a slope?",
     "On anything steeper than about 10%, loose round gravel will migrate downhill in heavy rain. Use angular crushed stone with fines, which locks together when compacted, and consider a border or a series of shallow cross drains to break up the water's run."],
    ["Do I need landscape fabric under gravel?",
     "For a driveway, a woven geotextile between the soil and the base course is worth it — it stops the stone from being pumped down into soft subgrade under traffic, which is the main way driveways fail. For a decorative bed, fabric mostly delays weeds for a few seasons and then becomes a nuisance when it tears."],
  ],
  sources: [["https://www.nssga.org/", "NSSGA — National Stone, Sand & Gravel Association"]],
  sourceNote: "Density figures are typical published ranges for loose delivered material, not a measurement of the load you receive. Moisture and gradation move the weight; confirm with your supplier before ordering by the ton.",
  related: relatedTo("stone", "sand", "rock", "mulch", "sqft"),
});

const stone = materialPage({
  path: "/stone-calculator/",
  h1: "Crushed Stone Calculator",
  title: "Crushed Stone Calculator – Tons, Yards & Coverage | Ruler Square",
  description: "Free crushed stone calculator for #57 stone, crusher run and paver base. Get tons, cubic yards, coverage and cost, with weights and depths shown.",
  lede: "Crushed stone in tons and cubic yards, with compaction for a base.",
  material: "crushed",
  materialName: "Crushed stone",
  noun: "crushed stone",
  lbPerYd3: 2700, lowTons: 1.3, highTons: 1.5,
  defaultDepth: 4, defaultCompaction: 20,
  depthHint: "4–6 in for a paver base",
  lastmod: "2026-09-22",
  intro: "Crushed stone is graded by number, and the number tells you the size of the screen it passed through. Getting the grade right matters more than getting the quantity exactly right — the wrong stone in a paver base will settle no matter how much of it you buy.",
  example: {
    label: "12 × 14 ft paver patio base, 5 inches deep",
    text: "The area is 12 × 14 = 168 square feet. Five inches is 0.417 feet, giving 168 × 0.417 = 70 cubic feet, or 2.59 cubic yards. Crushed stone weighs about 1.35 tons per cubic yard, so that is 3.5 tons. A compacted paver base needs 20% extra, so order 3.11 cubic yards — round up to 3.5 yards or 4.5 tons.",
  },
  depthProse: "Paver and patio bases need 4 inches over stable soil and 6 inches over clay or anywhere that freezes hard. Compact in 2-inch lifts rather than dumping the full depth at once — a plate compactor only densifies the top couple of inches, so a single thick lift stays loose underneath and the patio settles the first winter.",
  faq: [
    ["What is #57 stone used for?",
     "#57 is a washed stone roughly ¾ inch across with no fines in it. Because the fines are washed out, water runs straight through, which makes it the standard choice for French drains, drainage beds, septic fields and the drainage layer under a slab. That same property means it will not compact and lock, so it is the wrong stone for the top of a driveway."],
    ["What is the difference between crusher run and #57 stone?",
     "Crusher run (also sold as ABC, #411 or dense grade) contains stone dust and fines alongside the larger pieces. Those fines fill the voids and let the material compact into a hard, stable layer — which is why it is used for driveway bases and under pavers. #57 is washed clean of fines, so it drains freely but stays loose. Use crusher run where you need strength, #57 where you need drainage."],
    ["How much does a ton of crushed stone cover?",
     "At the assumed density of 2,700 lb per cubic yard, one US ton is about 0.74 cubic yard. Before allowance, that covers about 120 square feet at 2 inches deep, 80 at 3 inches or 60 at 4 inches. Your supplier’s density can change the result."],
  ],
  sources: [["https://www.nssga.org/", "NSSGA — National Stone, Sand & Gravel Association"]],
  sourceNote: "Density figures are typical published ranges for loose delivered material, not a measurement of the load you receive. Moisture and gradation move the weight; confirm with your supplier before ordering by the ton.",
  related: relatedTo("gravel", "sand", "rock", "concrete", "sqft"),
});

const sand = materialPage({
  path: "/sand-calculator/",
  h1: "Sand Calculator",
  title: "Sand Calculator – Cubic Yards, Tons & Bags | Ruler Square",
  description: "Free sand calculator for paver sand, bedding sand and sandboxes. Get cubic yards, tons, bags and cost, with coverage and weights shown.",
  lede: "Sand in cubic yards, tons or bags, for bedding, sandboxes or backfill.",
  material: "sand",
  materialName: "Sand",
  noun: "sand",
  lbPerYd3: 2700, lowTons: 1.3, highTons: 1.5,
  defaultDepth: 1, defaultCompaction: 0,
  depthHint: "1 in for paver bedding sand",
  lastmod: "2026-09-22",
  intro: "Sand is one of the few materials where ordering extra is a real mistake. A bedding layer under pavers is supposed to be exactly one inch — thicker, and the pavers sink unevenly no matter how well you compact the base beneath.",
  example: {
    label: "10 × 12 ft paver patio, 1 inch of bedding sand",
    text: "The area is 120 square feet. One inch is 0.083 feet, so the volume is 120 × 0.083 = 10 cubic feet, or 0.37 cubic yards. At about 1.35 tons per cubic yard, that is half a ton. Most suppliers have a minimum delivery, so for a job this size bagged sand from a home center is usually the cheaper route — 10 cubic feet is five 2-cubic-foot bags.",
  },
  depthProse: "Bedding sand under pavers is one inch, screeded flat and never compacted before the pavers go down. Sandboxes are filled 6–12 inches deep. Backfill and levelling layers vary with the job, but sand used as structural fill should go in 4–6 inch lifts and be compacted between each one.",
  faq: [
    ["What kind of sand goes under pavers?",
     "Coarse concrete sand, often sold as C33 or bedding sand. It has angular grains that interlock and hold the pavers steady. Do not use play sand or mason sand for bedding — the grains are fine and rounded, so the layer keeps shifting under load and the pavers go wavy within a season."],
    ["How many bags of sand are in a cubic yard?",
     "A cubic yard is 27 cubic feet. Retail sand is sold in 0.5 cubic foot bags (54 per yard) and 2 cubic foot bags (14 per yard). By weight, a 50 lb bag holds roughly 0.5 cubic feet, so a cubic yard is about 54 of them."],
    ["Does sand need to be compacted?",
     "It depends on the job. Bedding sand under pavers is screeded and left loose — the pavers are compacted into it afterwards, and pre-compacting it ruins the screed. Sand used as structural backfill does need compacting, in 4–6 inch lifts, or it will settle later and take whatever is on top with it."],
    ["How much does a yard of sand weigh?",
     "Dry sand weighs about 2,700 pounds per cubic yard, or 1.35 tons. Wet sand is noticeably heavier at roughly 3,240 pounds per cubic yard, because water fills the spaces between the grains. If your sand has been rained on, expect to get less volume than the weight ticket suggests."],
  ],
  sources: [["https://www.nssga.org/", "NSSGA — National Stone, Sand & Gravel Association"]],
  sourceNote: "Density figures are typical published ranges for loose delivered material, not a measurement of the load you receive. Moisture and gradation move the weight; confirm with your supplier before ordering by the ton.",
  related: relatedTo("gravel", "stone", "concrete", "sqft", "topsoil"),
});

const topsoil = materialPage({
  path: "/topsoil-calculator/",
  h1: "Topsoil Calculator",
  title: "Topsoil Calculator – Cubic Yards, Tons & Bags | Ruler Square",
  description: "Free topsoil calculator for lawns, garden beds and raised beds. Get cubic yards, tons, bags and cost, with depth guidance by project.",
  lede: "Topsoil in cubic yards, tons or bags, for lawns, beds or raised beds.",
  material: "topsoil",
  materialName: "Topsoil",
  noun: "topsoil",
  lbPerYd3: 2000, lowTons: 0.9, highTons: 1.3,
  defaultDepth: 4, defaultCompaction: 0,
  depthHint: "4–6 in for a new lawn",
  lastmod: "2026-09-22",
  intro: "Topsoil is the one bulk material where quality varies more than quantity. Screened topsoil, unscreened topsoil and garden blend are priced differently and behave differently, and the cheapest load is often mostly subsoil and clay.",
  example: {
    label: "30 × 40 ft new lawn, 4 inches deep",
    text: "An area of 1,200 square feet at 4 inches deep needs 400 cubic feet, or 14.81 cubic yards before allowance. At the assumed 2,000 lb per yard, that is 14.81 US tons. Ask the supplier to confirm the actual density and suitable delivery capacity.",
  },
  depthProse: "A new lawn needs 4–6 inches of topsoil over the subgrade to hold enough water and root depth to survive a dry August. Overseeding or top-dressing an existing lawn only needs a quarter to half an inch at a time — any more and you smother the grass you already have. Vegetable beds want 12 inches of good soil; raised beds are filled to their full depth.",
  faq: [
    ["How much does a yard of topsoil weigh?",
     "Screened, relatively dry topsoil weighs about 2,000 pounds per cubic yard — one ton. Wet topsoil can reach 2,700 pounds, and topsoil with a lot of clay in it is heavier again. Suppliers who sell by the ton rather than the yard do better on a rainy week, which is worth remembering when you compare quotes."],
    ["How deep should topsoil be for a new lawn?",
     "Four to six inches of topsoil over the prepared subgrade. Less than four and the lawn dries out fast in summer, because there is not enough soil to hold water. Rototill the top inch or two of the existing subgrade before spreading, so the layers knit together rather than forming a hard boundary that roots will not cross."],
    ["What is the difference between topsoil, garden soil and compost?",
     "Topsoil is mineral soil, screened to take out rocks and roots, and it is the bulk of what you spread. Compost is decomposed organic matter, used as an amendment rather than on its own — plants in pure compost usually do badly. Garden soil or garden blend is topsoil pre-mixed with compost, typically around 70/30, and costs more per yard than plain topsoil."],
    ["How many bags of topsoil are in a cubic yard?",
     "Retail topsoil comes in 0.75 and 1 cubic foot bags, so a cubic yard is 36 of the small bags or 27 of the large ones. Bagged soil costs several times what bulk does per cubic yard, so anything over about one yard is worth having delivered."],
  ],
  sources: [["https://www.nrcs.usda.gov/", "USDA NRCS — soil survey and soil science resources"]],
  sourceNote: "Density figures are typical published ranges for loose delivered material, not a measurement of the load you receive. Moisture and gradation move the weight; confirm with your supplier before ordering by the ton.",
  related: relatedTo("mulch", "dirt", "gravel", "sqft", "stone"),
});

const dirt = materialPage({
  path: "/fill-dirt-calculator/",
  h1: "Fill Dirt Calculator",
  title: "Fill Dirt Calculator – Cubic Yards, Tons & Cost | Ruler Square",
  description: "Free fill dirt calculator for grading, low spots and backfill. Estimate cubic yards, tons and material cost with editable density and volume allowance.",
  lede: "Estimate cubic yards and tons of fill dirt for grading, low spots or backfill.",
  material: "fill-dirt",
  materialName: "Fill dirt",
  noun: "fill dirt",
  lbPerYd3: 2000, lowTons: 1.0, highTons: 1.4,
  defaultDepth: 6, defaultCompaction: 25,
  depthHint: "measure the deepest point, then average",
  lastmod: "2026-09-22",
  intro: "Fill dirt is the cheap structural material you use to change the shape of the ground — not to grow anything in. It is subsoil with the organic matter screened out, which is exactly what you want under a patio or a foundation and exactly what you do not want under a lawn.",
  example: {
    label: "25 × 30 ft low spot, averaging 8 inches deep",
    text: "A 750-square-foot area at an average 8-inch depth needs 500 cubic feet, or 18.52 cubic yards. A 25% planning allowance gives 23.15 cubic yards. At the assumed 2,000 lb per yard, that is 23.15 US tons. Half-yard rounding gives 23.5 yards; ask the supplier to confirm density, allowance and delivery capacity.",
  },
  depthProse: "Fill depth is rarely uniform, which is where most estimates go wrong. Measure the depth at the deepest point and at several points around the edge, then average them — for a bowl-shaped low spot, the average is usually around half the maximum depth. Place fill in 6–8 inch lifts and compact between each one; anything thicker will not densify properly and will settle for years.",
  faq: [
    ["What is the difference between fill dirt and topsoil?",
     "Fill dirt is subsoil with the organic material screened out. Because there is nothing in it to decompose, it stays put once compacted, which is what you want underneath a structure. Topsoil is full of organic matter, which is why things grow in it and also why it keeps settling as that matter breaks down. Never use topsoil as structural fill, and never expect anything to grow in fill dirt."],
    ["How much does fill dirt cost?",
     "Fill dirt is the cheapest bulk material there is, typically $5–$25 per cubic yard for the material itself. Most of what you pay is hauling. If there is an excavation project nearby, contractors often give clean fill away free to avoid disposal fees — it is worth asking around before you buy."],
    ["How much does fill dirt settle?",
     "Uncompacted fill can settle 10–25% over the first couple of years, more if it went in wet or in thick lifts. Compacting in 6–8 inch lifts brings that down to a few percent. If you are filling under anything solid — a slab, a patio, a foundation — compaction is not optional, and a compaction test is worth the money."],
    ["How many truckloads of fill dirt do I need?",
     "Ask the hauler for usable capacity in both cubic yards and pounds for this material. Divide your order by the smaller weight-limited or volume-limited capacity and round up. Truck sizes, road limits and moisture vary; this calculator does not assign a safe truck load."],
  ],
  sources: [["https://www.nrcs.usda.gov/", "USDA NRCS — soil survey and soil science resources"]],
  sourceNote: "Density figures are typical published ranges for loose delivered material, not a measurement of the load you receive. Moisture and gradation move the weight; confirm with your supplier before ordering by the ton.",
  related: relatedTo("topsoil", "gravel", "sqft", "stone", "sand"),
});


const mulch = materialPage({
  path: "/mulch-calculator/",
  h1: "Mulch Calculator",
  title: "Mulch Calculator – Cubic Yards, Bags & Cost | Ruler Square",
  description: "Free mulch calculator for garden beds and landscaping. Get cubic yards, 2 cu ft bags and cost, with depth guidance and coverage tables.",
  lede: "Mulch in cubic yards or bags, plus material cost before delivery.",
  material: "mulch",
  materialName: "Bark mulch",
  noun: "mulch",
  lbPerYd3: 800, lowTons: 0.3, highTons: 0.5,
  defaultDepth: 3, defaultCompaction: 0,
  depthHint: "3 in is the usual for established beds",
  lastmod: "2026-09-22",
  intro: "Mulch is the one bulk material where buying too much is cheap and spreading too much is expensive — piled deeper than about four inches it starves roots of air and holds water against stems until they rot.",
  example: {
    label: "400 sq ft of beds, 3 inches deep",
    text: "Three inches is 0.25 feet, so the volume is 400 × 0.25 = 100 cubic feet, or 100 ÷ 27 = 3.7 cubic yards. Mulch is light at roughly 0.4 tons per cubic yard, so that is about 1.5 tons. In 2 cubic foot bags it would be 50 bags — which is why anything over about two yards is worth having delivered in bulk.",
  },
  depthProse: "Two to three inches is right for established beds. Three to four inches on new beds, where you are also trying to suppress weeds. Never pile it against trunks or stems — the volcano of mulch around a tree base is the single most common landscaping mistake, and it kills the tree slowly by keeping the bark permanently wet.",
  faq: [
    ["How many bags of mulch are in a cubic yard?",
     "A cubic yard is 27 cubic feet, so it takes 14 bags of the standard 2 cubic foot size, or 9 bags of 3 cubic feet. Bagged mulch typically costs two to three times as much per yard as bulk delivery, so the break-even is around two cubic yards."],
    ["How deep should mulch be?",
     "Two to three inches for established beds, three to four for new ones. Deeper than four inches and water struggles to reach the soil while the mulch layer itself stays soggy. Top up annually rather than adding a full new layer over the old one."],
    ["What is the difference between hardwood, cedar and dyed mulch?",
     "Hardwood mulch breaks down fastest and feeds the soil as it goes, so it needs topping up every year. Cedar resists rot and insects and lasts two to three years, at a higher price. Dyed mulch is usually ground pallet wood coloured with iron oxide or carbon — it holds colour longest but adds nothing to the soil."],
    ["When is the best time to mulch?",
     "Mid to late spring, once the soil has warmed. Mulching too early traps the cold and delays growth. A second light top-up in late autumn helps insulate roots over winter in cold zones."],
  ],
  sources: [["https://www.arborday.org/", "Arbor Day Foundation — mulching and tree-care guidance"]],
  sourceNote: "Density figures are typical published ranges for loose delivered material, not a measurement of the load you receive. Moisture and gradation move the weight; confirm with your supplier before ordering by the ton.",
  related: relatedTo("topsoil", "gravel", "stone", "rock", "sqft"),
});

const rock = materialPage({
  path: "/river-rock-calculator/",
  h1: "River Rock Calculator",
  title: "River Rock Calculator – Tons, Yards & Coverage | Ruler Square",
  description: "Free river rock calculator for landscaping and drainage. Get tons, cubic yards, coverage and cost, with size and depth guidance.",
  lede: "River rock in tons and cubic yards, and what it covers at each depth.",
  material: "river-rock",
  materialName: "River rock",
  noun: "river rock",
  lbPerYd3: 2700, lowTons: 1.3, highTons: 1.5,
  defaultDepth: 3, defaultCompaction: 0,
  depthHint: "2–3 in for decorative beds",
  lastmod: "2026-09-22",
  intro: "River rock is smooth, rounded stone sold by size grade. It never locks together the way crushed stone does, which makes it excellent for drainage and dry creek beds and a poor choice anywhere it has to carry weight.",
  example: {
    label: "dry creek bed, 30 ft long and 3 ft wide, 4 inches deep",
    text: "The area is 90 square feet. At 4 inches deep, the volume is 30 cubic feet, or 1.11 cubic yards. At the assumed density of 2,700 lb per yard, that is 1.5 US tons before rounding. If your supplier sells half-yard increments, 1.5 yards would weigh about 4,050 lb. Arrange suitable delivery; do not assume a pickup can carry it.",
  },
  depthProse: "Decorative beds take two to three inches — enough to hide the fabric beneath without burying plants. Dry creek beds and drainage swales want four to six inches so water moves through the stone rather than over it. Do not use river rock on a driveway: round stone under tyres migrates immediately and ends up in the lawn.",
  faq: [
    ["What size river rock should I use?",
     "¾ to 1½ inch is the general-purpose landscaping size and the easiest to walk on. Two to three inch works for larger beds and slows water in a swale. Anything above four inches is decorative or for erosion control — it is uncomfortable underfoot and awkward to rake."],
    ["Does river rock need landscape fabric underneath?",
     "Yes, more than mulch does. River rock does not decompose, so once weeds come up through it you cannot simply replace the layer — you have to lift and wash the stone. A woven geotextile under it is worth the extra cost."],
    ["Is river rock cheaper than mulch?",
     "It costs considerably more up front — often $65 to $180 per cubic yard delivered against $30 to $60 for mulch. It wins over time because it never needs replacing, so the break-even is usually somewhere around year four or five."],
  ],
  sources: [["https://www.nssga.org/", "NSSGA — National Stone, Sand & Gravel Association"]],
  sourceNote: "Density figures are typical published ranges for loose delivered material, not a measurement of the load you receive. Moisture and gradation move the weight; confirm with your supplier before ordering by the ton.",
  related: relatedTo("gravel", "stone", "mulch", "sand", "sqft"),
});

const asphalt = materialPage({
  path: "/asphalt-calculator/",
  h1: "Asphalt Calculator",
  title: "Asphalt Calculator – Tons of Hot Mix & Cost | Ruler Square",
  description: "Free asphalt calculator for driveways, lots and overlays. Get tons of hot mix, cubic yards and cost, with thickness guidance and coverage tables.",
  lede: "Tons of hot mix asphalt for your paved area, and what it costs.",
  material: "asphalt",
  materialName: "Hot mix asphalt",
  noun: "asphalt",
  lbPerYd3: 3915, lowTons: 1.9, highTons: 2.1,
  defaultDepth: 3, defaultCompaction: 0,
  depthHint: "2–3 in for a residential driveway",
  lastmod: "2026-09-22",
  intro: "Asphalt is quoted and delivered by the ton, but you measure your job in square feet, so every asphalt estimate is a weight conversion. Compacted hot mix runs about 145 pounds per cubic foot, which works out to 2 tons per cubic yard — heavier than any of the loose aggregates.",
  example: {
    label: "100 × 20 ft driveway, 3 inches thick",
    text: "The area is 2,000 square feet. Three inches is 0.25 feet, so the volume is 2,000 × 0.25 = 500 cubic feet. At 145 pounds per cubic foot that is 72,500 pounds, or 36.25 tons. Asphalt does not need a compaction allowance the way loose gravel does, because the 145 lb figure is already the compacted density — the paver and roller do that work.",
  },
  depthProse: "Residential driveways are normally paved 2 to 3 inches of surface course over a 6 to 8 inch compacted aggregate base. Commercial lots carrying delivery trucks go 3 to 4 inches over a deeper base. An overlay on sound existing asphalt can be as little as 1.5 inches. The base matters more than the asphalt: a thick mat over a weak base cracks anyway.",
  faq: [
    ["How many tons of asphalt do I need for a driveway?",
     "For a typical residential driveway at 3 inches thick, plan on about 0.018 tons per square foot. A 20 × 50 ft driveway (1,000 square feet) needs roughly 18 tons. Multiply your area by the thickness in feet, then by 145 pounds per cubic foot, then divide by 2,000."],
    ["How much does a ton of asphalt cover?",
     "One ton covers about 80 square feet at 2 inches thick, 55 square feet at 3 inches, or 40 square feet at 4 inches. Those are the figures most paving contractors work from when they quote."],
    ["How much does asphalt paving cost?",
     "Hot mix material typically runs $100 to $160 per ton in 2026. Installed, including base preparation, expect $7 to $15 per square foot for a residential driveway. Resurfacing an existing driveway costs considerably less than building one from bare ground, because the base is already there."],
    ["What thickness should an asphalt driveway be?",
     "Two to three inches of surface course over six to eight inches of compacted aggregate base for cars and light trucks. Go to four inches of asphalt and a deeper base if heavy vehicles will use it regularly. Skimping on the base to afford thicker asphalt is the wrong trade — the base carries the load."],
  ],
  sources: [["https://www.asphaltpavement.org/", "NAPA — National Asphalt Pavement Association"]],
  sourceNote: "Density figures are typical published ranges for loose delivered material, not a measurement of the load you receive. Moisture and gradation move the weight; confirm with your supplier before ordering by the ton.",
  related: relatedTo("gravel", "stone", "concrete", "sqft", "sand"),
});

const roadbase = materialPage({
  path: "/road-base-calculator/",
  h1: "Road Base Calculator",
  title: "Road Base Calculator – Tons, Yards & Compaction | Ruler Square",
  description: "Free road base calculator for driveways and paver bases. Get tons and cubic yards of crusher run, with the compaction allowance that most estimates miss.",
  lede: "Work out the tons and cubic yards of road base you need, with compaction included.",
  material: "abc",
  materialName: "Crusher run road base",
  noun: "road base",
  lbPerYd3: 3000, lowTons: 1.4, highTons: 1.8,
  defaultDepth: 6, defaultCompaction: 25,
  depthHint: "6–8 in for a driveway base",
  lastmod: "2026-09-22",
  intro: "Road base is crushed stone with the fines left in, sold as crusher run, ABC or dense grade depending on where you are. Those fines are the point: they fill the voids so the material locks into a hard layer under compaction, which washed stone never does.",
  example: {
    label: "40 × 12 ft driveway base, 6 inches deep",
    text: "The area is 480 square feet. Six inches is 0.5 feet, so the loose volume is 240 cubic feet, or 8.89 cubic yards. Road base compacts hard, so add 25%: 11.1 cubic yards. At about 1.5 tons per cubic yard that is 16.7 tons — close to a full tandem dump truck load.",
  },
  depthProse: "Six to eight inches compacted is the normal driveway base over stable soil, and ten to twelve over clay or anywhere with a hard freeze. Place it in lifts of no more than four inches and compact each one. A single thick lift only densifies near the surface, leaving loose material underneath that settles into ruts the first wet season.",
  faq: [
    ["What is the difference between road base and gravel?",
     "Road base is crushed and graded with the stone dust left in, so the particles interlock and compact into a solid layer. Clean gravel has the fines washed out, so it drains well but stays loose forever. Use road base where you need strength, clean stone where you need drainage."],
    ["How thick should road base be under pavers?",
     "Four to six inches compacted over stable soil, six to eight over clay or in a freeze-thaw climate. Compact in two-inch lifts — a plate compactor only works on the top couple of inches."],
    ["Do I need to compact road base?",
     "Yes, and it is not optional. Uncompacted base settles unevenly under load, which is what produces ruts in a driveway and a wavy paver patio. Hire a plate compactor or a roller; driving over it with a truck is not compaction."],
  ],
  sources: [["https://www.nssga.org/", "NSSGA — National Stone, Sand & Gravel Association"]],
  sourceNote: "Density figures are typical published ranges for loose delivered material. Crusher run varies by quarry and moisture; confirm with your supplier before ordering by the ton.",
  related: relatedTo("gravel", "stone", "asphalt", "sand", "sqft"),
});

module.exports = [gravel, stone, sand, topsoil, dirt, mulch, rock, asphalt, roadbase];
